name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: brew install sdl3 libsoxr

      - name: Print build configuration
        run: make info

      - name: Build
        run: make
